# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      
      # Runs a set of commands using the runners shell
      - name: Install Curl
        run: |
          sudo apt-get update
          sudo apt-get install curl
          sudo apt autoremove
          
      # Runs a single command using the runners shell
      - name: Install Repo
        run: |
          mkdir ~/bin 
          PATH=~/bin:$PATH
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && chmod a+x ~/bin/repo
          repo init --depth=1 -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r46
          # gpg --recv-key 8BB9AD793E8E6153AF0F9A4416530D5E920F5C65
          # curl https://storage.googleapis.com/git-repo-downloads/repo.asc | gpg --verify - ~/bin/repo
          
      
